project_id = "thxkzaazwkdtacfvdiyn"

[functions.pin-login]
verify_jwt = false

[functions.configure-replicate]
verify_jwt = true

[functions.generate-botanical-content]
verify_jwt = true

[functions.generate-botanical-resume]
verify_jwt = true

[functions.regenerate-visual]
verify_jwt = true

[functions.regenerate-caption]
verify_jwt = true

[functions.queue-moderation]
verify_jwt = true

[functions.post-tiktok-carousel]
verify_jwt = true

[functions.tiktok-send-status]
verify_jwt = true

[functions.tiktok-oauth]
verify_jwt = false
