// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-plants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
import { z } from "npm:zod@^4.4.3";
var list_plants_default = defineTool({
  name: "list_plants",
  title: "List botanical posts",
  description: "List the most recent botanical content posts (plant name, id, virality score, queue status).",
  inputSchema: {
    limit: z.number().int().optional().describe("Max rows to return (1-100). Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const env = globalThis.Deno?.env;
    const supabase = createClient(
      env?.get("SUPABASE_URL") ?? "",
      env?.get("SUPABASE_PUBLISHABLE_KEY") ?? env?.get("SUPABASE_ANON_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const cap = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data, error } = await supabase.from("botanical_content").select("id, plant_name, virality_score, queue_status, created_at").order("created_at", { ascending: false }).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-plant.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_plant_default = defineTool2({
  name: "get_plant",
  title: "Get botanical post",
  description: "Fetch a full botanical content row by id, including script, caption, and verified fact.",
  inputSchema: {
    id: z2.string().uuid().describe("botanical_content row id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const env = globalThis.Deno?.env;
    const supabase = createClient2(
      env?.get("SUPABASE_URL") ?? "",
      env?.get("SUPABASE_PUBLISHABLE_KEY") ?? env?.get("SUPABASE_ANON_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("botanical_content").select(
      "id, plant_name, verified_fact, script, caption, part2_hook, virality_score, score_reasoning, queue_status, created_at"
    ).eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/list-trends.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_trends_default = defineTool3({
  name: "list_trends",
  title: "List trend posts",
  description: "List the most recent trend content rows (subject, verified fact, id).",
  inputSchema: {
    limit: z3.number().int().optional().describe("Max rows to return (1-100). Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const cap = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data, error } = await supabase.from("trend_content").select("id, subject, verified_fact, created_at").order("created_at", { ascending: false }).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "botanical-studio-mcp",
  title: "Botanical Studio",
  version: "0.1.0",
  instructions: "Read-only access to the Botanical Studio content library. Use `list_plants` to browse recent botanical posts, `get_plant` to fetch a single post's script and caption by id, and `list_trends` for trend research rows.",
  tools: [list_plants_default, get_plant_default, list_trends_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
